version: "3.9"
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
     MYSQL_ROOT_PASSWORD: Arkham78
     MYSQL_DATABASE: patients
     MYSQL_USER: root
     MYSQL_PASSWORD: Arkham78
    volumes:
      - ./dbdata:/var/lib/mysql/
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  instance1:
    build:
      context: ""
    links:
      - kafka
      - db
    depends_on:
      - kafka
      - db
    ports:
      - 8090:8090
    environment:
      - SPRING_CONFIG_NAME=application
      - SPRING_DATASOURCE.DRIVERCLASSNAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/patients
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Arkham78
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS=kafka:9092
  consumer1:
    build:
      context: ""
    environment:
      - SPRING_CONFIG_NAME=consumer1
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS=kafka:9092
      - SPRING.KAFKA.CONSUMER.GROUP-ID=myGroup
      - SPRING_DATASOURCE.DRIVERCLASSNAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/patients
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Arkham78
      - SPRING_PROFILES_ACTIVE=consumer
    links:
      - kafka
      - db
    depends_on:
      - kafka
      - db
    ports:
      - 9090:9090
